
$HOME/.config/home-manager/home.nix:
  nix-channel --add https://github.com/nix-community/home-manager/archive/release-23.11.tar.gz home-manager
  nix-channel update
  nix-shell '<home-manager>' -A install
  sed -
